### ISSUE TITLE
Missing Dependency: jetty-alpn-agent when building for the first time

### ISSUE THREAD

**Issue by catshow** [chhsiao90/nitmproxy#10]
When trying to run for the first time the jetty-alpn-agent jar is not in my maven repo.  Please add a dependency to pull it into maven so it will run.  

I am not allowed to contribute to OSS projects, otherwise I would do a PR.

Thanks

**Comment by chhsiao90** [comment]
I'm considering to remove the jetty-alpn-agent from nitmproxy, because the alpn api was already backported to java 1.8 since 8u252. So this dependency is no longer required for supporting alpn if we keep the jdk updated.

What do you thin?

see https://github.com/jetty-project/jetty-alpn#option-1---enforce-openjdk-8u252-or-later

**Comment by chhsiao90** [comment]
Fixed by #12
